import Joking as j
rj = j.random_joke()
pj = j.programming_joke()
dj = j.random_dad_joke()
jod = j.JOD()
#print(rj)
responses = [
    ["hello", "Hi there! How can I help you today?"],
    ["hi", "Hello! How can I assist you?"],
    ["how are you", "I'm doing great, thank you for asking! How about you?"],
    ["what is your name", "My name is Bhaarat A.I . I am your assistant. You can call me whatever you like!"],
    ["who created you", "I had been created and devloped by Ishant yadav sir . I thanks him to creating me for helping you"],
    ["who are you", "I'm an AI assistant here to help you with your queries."],
    ["how can you help me", "I can assist with answering questions, opening programs, and much more!"],
    ["tell me  joke", rj],
    ["tell me programming joke", jod],
    ["tell me programing joke", pj],
    ["tell me dad joke", dj],
    ["good morning", "Good morning! How can I help you today?"],
    ["good evening", "Good evening! What can I do for you?"],
    ["good night", "Good night! Sweet dreams!"],
    ["thank you", "You're welcome! Let me know if you need anything else."],
    ["thanks", "You're welcome! Feel free to ask anything."],
    ["sorry", "No problem! How can I assist you further?"],
    ["help", "I'm here to help! Please tell me what you need."],
    ["what is your favorite color", "I don't have a favorite color, but I like all the colors!"],
    ["who is the president of the united states", "The current President of the United States is Joe Biden."],
    ["who is the prime minister of india", "The Prime Minister of India is Narendra Modi."],
    ["what is python", "Python is a high-level programming language known for its readability and versatility in various applications."],
    ["what is javascript", "JavaScript is a programming language that is commonly used to create interactive effects within web browsers."],
    ["what is java", "Java is a popular programming language that is used for building cross-platform applications, including mobile apps."],
    ["what is c programming", "C is a general-purpose, procedural programming language that was designed for system and application software."],
    ["what is c++", "C++ is an object-oriented programming language that is widely used for building high-performance software and applications."],
    ["what is html", "HTML stands for HyperText Markup Language. It is the standard language used for creating and structuring web pages."],
    ["what is css", "CSS stands for Cascading Style Sheets. It is used to style and format the layout of web pages."],
    ["what is react", "React is a JavaScript library for building user interfaces, particularly single-page applications."],
    ["what is angular", "Angular is a platform and framework for building single-page client applications using HTML and TypeScript."],
    ["what is vue", "Vue.js is a progressive JavaScript framework for building user interfaces."],
    ["what is nodejs", "Node.js is a runtime environment that allows JavaScript to be used for server-side scripting."],
    ["what is mongodb", "MongoDB is a NoSQL database that stores data in flexible, JSON-like documents."],
    ["what is firebase", "Firebase is a platform developed by Google for creating mobile and web applications with real-time databases and authentication."],
    ["what is git", "Git is a version control system used for tracking changes in source code during software development."],
    ["what is github", "GitHub is a platform for hosting and collaborating on Git repositories."],
    ["what is docker", "Docker is a platform for developing, shipping, and running applications in lightweight containers."],
    ["what is kubernetes", "Kubernetes is an open-source platform designed to automate the deployment, scaling, and management of containerized applications."],
    ["what is a server", "A server is a computer system or program that provides services or resources to other computers or programs in a network."],
    ["what is a client", "A client is a computer or program that requests services or resources from a server."],
    ["what is cloud computing", "Cloud computing is the delivery of computing services such as storage, processing, and networking over the internet."],
    ["what is a database", "A database is an organized collection of data, typically stored and accessed electronically from a computer system."],
    ["what is SQL", "SQL (Structured Query Language) is a domain-specific language used for managing and querying relational databases."],
    ["what is nosql", "NoSQL refers to a type of database that does not use the traditional relational model, and it is designed for scalability and flexibility."],
    ["what is web development", "Web development is the process of creating websites and web applications that are accessible through the internet."],
    ["what is software development", "Software development is the process of designing, creating, testing, and maintaining software applications."],
    ["what is an algorithm", "An algorithm is a set of steps or rules used to solve a problem or perform a task."],
    ["what is a data structure", "A data structure is a way of organizing and storing data for efficient access and modification."],
    ["what is big data", "Big data refers to large volumes of data that require advanced tools and techniques to process and analyze."],
    ["what is the internet", "The internet is a global network of interconnected computers that communicate using standardized protocols."],
    ["what is a website", "A website is a collection of web pages that are accessed through the internet using a web browser."],
    ["what is a web application", "A web application is an interactive application that runs in a web browser and requires internet connectivity."],
    ["what is an api", "An API (Application Programming Interface) allows different software systems to communicate and exchange data."],
    ["what is oauth", "OAuth is an open standard for authorization that allows access to user data without sharing credentials."],
    ["what is a url", "A URL (Uniform Resource Locator) is the address used to access a resource on the internet."],
    ["what is a vpn", "A VPN (Virtual Private Network) is a service that encrypts your internet connection to protect privacy and security."],
    ["what is encryption", "Encryption is the process of converting data into a coded format to prevent unauthorized access."],
    ["what is a firewall", "A firewall is a network security system that monitors and controls incoming and outgoing network traffic based on predetermined security rules."],
    ["what is 2fa", "2FA (Two-Factor Authentication) is a security system that requires two forms of identification to access an account or service."],
    ["what is a bot", "A bot is an automated software application designed to perform tasks without human intervention."],
    ["what is automation", "Automation refers to using technology to perform tasks or processes with minimal human intervention."],
    ["what is artificial intelligence", "Artificial intelligence is the simulation of human intelligence in machines that can perform tasks like learning, problem-solving, and decision-making."],
    ["what is deep web", "The deep web refers to parts of the internet that are not indexed by search engines, such as databases and private websites."],
    ["what is dark web", "The dark web is a part of the deep web that requires special software (like Tor) to access and is often associated with illegal activities."],
    ["how do you make a website", "To make a website, you need to learn HTML, CSS, and JavaScript, and use web development tools or frameworks to build it."],
    ["how do you learn programming", "To learn programming, start by choosing a language (like Python or JavaScript) and practice solving problems, building projects, and reading documentation."],
    ["how do you start coding", "To start coding, pick a programming language and use online tutorials, courses, and resources to begin writing code."],
    ["how do I become a programmer", "To become a programmer, choose a programming language, practice coding regularly, work on projects, and stay up-to-date with industry trends."],
    ["how do you make money online", "You can make money online by freelancing, creating content, selling products, or offering services through various platforms."],
    ["what is freelancing", "Freelancing is a type of work where individuals offer their services to clients on a project basis, often remotely."],
    ["what is a startup", "A startup is a company or organization in the early stages of operations, typically focused on developing a unique product or service."],
    ["what is an entrepreneur", "An entrepreneur is someone who starts and runs a business, often taking on financial risks in the pursuit of profit."],
    ["how can I improve my skills", "To improve your skills, practice regularly, take courses, seek feedback, and stay curious about new developments in your field."],
    ["how can I get better at coding", "To get better at coding, practice solving problems, build real-world projects, learn data structures and algorithms, and read other people's code."],
    ["what is freelancing", "Freelancing is when individuals work independently on various projects and tasks, usually on a contract or short-term basis."],
    ["how do I learn to code", "Start by selecting a beginner-friendly programming language like Python, take online courses, and practice coding regularly."],
    ["how do I learn programming", "Start by learning a simple language like Python or JavaScript. Work on projects and solve coding problems to improve your skills."],
    ["how can I improve my coding skills", "You can improve your coding skills by practicing regularly, working on projects, and learning data structures and algorithms."],
    ["what is data science", "Data science is the field of study that uses scientific methods, processes, algorithms, and systems to extract knowledge and insights from structured and unstructured data."],
    ["what is machine learning", "Machine learning is a branch of artificial intelligence that allows systems to learn from data and improve over time without being explicitly programmed."],
    ["what is deep learning", "Deep learning is a subset of machine learning that uses neural networks with many layers to analyze complex data patterns."],
    ["what is artificial intelligence", "Artificial intelligence (AI) refers to the simulation of human intelligence in machines to perform tasks that typically require human cognition, like learning, problem-solving, and decision-making."],
    ["what is a neural network", "A neural network is a machine learning model inspired by the way the human brain processes information, consisting of layers of interconnected nodes."],
    ["what is a chatbot", "A chatbot is an AI-powered program that can simulate conversations with users, typically used for customer service or assistance."],
    ["what is a virtual assistant", "A virtual assistant is a software application that uses artificial intelligence to perform tasks or services for a user, often through voice or text commands."],
    ["what is natural language processing", "Natural language processing (NLP) is a field of AI that focuses on enabling computers to understand, interpret, and generate human language."],
    ["what is sentiment analysis", "Sentiment analysis is a technique used in natural language processing to determine the emotional tone behind words, often used to analyze social media, reviews, and customer feedback."],
    ["what is data visualization", "Data visualization is the graphical representation of data to help people understand and analyze patterns, trends, and insights from datasets."],
    ["what is blockchain", "Blockchain is a decentralized, distributed ledger technology that records transactions across multiple computers, ensuring security and transparency."],
    ["what is cryptocurrency", "Cryptocurrency is a type of digital or virtual currency that uses cryptography for security and operates independently of a central authority like a government."],
    ["what is bitcoin", "Bitcoin is a decentralized cryptocurrency that was invented in 2008 by an anonymous person or group known as Satoshi Nakamoto. It operates without a central authority or bank."],
    ["what is ethereum", "Ethereum is a decentralized, open-source blockchain platform that supports smart contracts and decentralized applications (DApps)." ],
    ["what is a smart contract", "A smart contract is a self-executing contract with the terms of the agreement directly written into code, which automatically enforces and executes the contract's terms."],
    ["what is a cryptocurrency wallet", "A cryptocurrency wallet is a software application used to store and manage private keys, public keys, and cryptocurrencies."],
    ["what is a token", "A token is a digital asset issued on a blockchain that represents ownership or a stake in a specific asset, service, or project."],
    ["what is mining", "Mining is the process of validating transactions and adding them to a blockchain, typically by solving complex mathematical puzzles. It is a key component of many cryptocurrencies."],
    ["what is a decentralized application", "A decentralized application (DApp) is an application that runs on a decentralized network, typically using blockchain technology."],
    ["what is the internet of things", "The Internet of Things (IoT) refers to a network of physical devices that are connected to the internet, allowing them to collect and exchange data."],
    ["what is 5g", "5G is the fifth generation of mobile network technology, offering faster speeds, lower latency, and the ability to connect more devices simultaneously."],
    ["what is the cloud", "The cloud refers to remote servers and services that provide storage, computing power, and other resources over the internet, rather than relying on local hardware."],
    ["what is a server", "A server is a computer or software system that provides resources or services to other computers or clients in a network."],
    ["what is a client", "A client is a computer or software that requests services or resources from a server."],
    ["what is a url", "A URL (Uniform Resource Locator) is the web address used to identify a resource on the internet."],
    ["what is html", "HTML (HyperText Markup Language) is the standard markup language used to create and design web pages."],
    ["what is css", "CSS (Cascading Style Sheets) is used to style the visual presentation of web pages, including layout, colors, and fonts."],
    ["what is javascript", "JavaScript is a programming language used to create dynamic and interactive content on web pages."],
    ["what is python", "Python is a high-level programming language known for its simplicity, readability, and versatility in web development, data science, and automation."],
    ["what is c", "C is a general-purpose programming language that was developed in the 1970s and is used for system and application programming."],
    ["what is c++", "C++ is a high-level programming language that is an extension of C, adding object-oriented features such as classes and inheritance."],
    ["what is java", "Java is a versatile, object-oriented programming language used for building web applications, mobile apps, and enterprise software."],
    ["what is ruby", "Ruby is a dynamic, object-oriented programming language known for its simplicity and ease of use, often used in web development."],
    ["what is swift", "Swift is a programming language developed by Apple for building iOS and macOS applications."],
    ["what is kotlin", "Kotlin is a modern, statically-typed programming language that is used for Android app development and is fully interoperable with Java."],
    ["what is go", "Go, also known as Golang, is an open-source programming language developed by Google that is designed for efficient system and network programming."],
    ["what is rust", "Rust is a systems programming language focused on performance, safety, and concurrency, often used for building high-performance software."],
    ["what is sql", "SQL (Structured Query Language) is a standard language used to interact with relational databases, including querying, inserting, and modifying data."],
    ["what is nosql", "NoSQL refers to a category of database management systems that do not use traditional relational models and are designed for scalability and flexibility."],
    ["what is mongodb", "MongoDB is a NoSQL, document-oriented database that uses JSON-like structures to store data."],
    ["what is redis", "Redis is an open-source, in-memory data structure store that is often used as a cache, message broker, and database."],
    ["what is firebase", "Firebase is a platform developed by Google for building mobile and web applications, providing services like real-time databases and authentication."],
    ["what is aws", "AWS (Amazon Web Services) is a comprehensive cloud computing platform provided by Amazon, offering services such as computing power, storage, and databases."],
    ["what is azure", "Azure is a cloud computing platform and service created by Microsoft that provides a variety of cloud services, including compute, analytics, storage, and networking."],
    ["what is google cloud", "Google Cloud is a suite of cloud computing services offered by Google, providing tools for computing, storage, machine learning, and more."],
    ["what is docker", "Docker is an open-source platform used to build, ship, and run applications inside containers, which are isolated environments for running software."],
    ["what is kubernetes", "Kubernetes is an open-source container orchestration platform that automates the deployment, scaling, and management of containerized applications."],
    ["what is a virtual machine", "A virtual machine (VM) is a software-based emulation of a physical computer that runs an operating system and applications."],
    ["what is an operating system", "An operating system (OS) is system software that manages computer hardware and software resources and provides common services for computer programs."],
    ["what is windows", "Windows is a series of operating systems developed by Microsoft, commonly used on personal computers and laptops."],
    ["what is linux", "Linux is an open-source, Unix-like operating system kernel that is used as the foundation for various operating systems."],
    ["what is macos", "macOS is an operating system developed by Apple for Macintosh computers, known for its sleek design and user-friendly interface."],
    ["what is ubuntu", "Ubuntu is a popular, open-source Linux distribution based on Debian, designed for ease of use and accessibility."],
    ["what is a firewall", "A firewall is a security system that monitors and controls incoming and outgoing network traffic based on predetermined security rules."],
    ["what is antivirus software", "Antivirus software is designed to detect, prevent, and remove malicious software (malware) from a computer system."],
    ["what is a router", "A router is a device that forwards data packets between computer networks, directing traffic across the internet or a local network."],
    ["what is an ip address", "An IP (Internet Protocol) address is a unique string of numbers assigned to each device connected to a computer network, identifying and locating it."],
    ["what is a domain name", "A domain name is a human-readable address used to identify a website, which maps to an IP address that computers use to locate the site."],
    ["what is a dns server", "A DNS (Domain Name System) server translates domain names into IP addresses so that browsers can load internet resources."],
    ["what is the internet", "The internet is a global network of interconnected computers and servers that use standardized protocols to communicate and share data."],
    ["what is a web server", "A web server is a system that hosts websites and serves web pages to users' browsers via HTTP or HTTPS protocols."],
    ["what is a proxy server", "A proxy server acts as an intermediary between a user's device and the internet, used for filtering content, privacy, or performance reasons."],
    ["what is ssl", "SSL (Secure Sockets Layer) is a cryptographic protocol used to provide secure communications over a computer network, particularly for online transactions."],
    ["what is tls", "TLS (Transport Layer Security) is a cryptographic protocol that provides secure communication over a computer network, succeeding SSL."],
    ["what is an api", "An API (Application Programming Interface) is a set of protocols and tools that allow different software applications to communicate with each other."],
    ["what is rest", "REST (Representational State Transfer) is an architectural style for designing networked applications that use HTTP requests to access and manipulate data."],
    ["what is soap", "SOAP (Simple Object Access Protocol) is a protocol used for exchanging structured information in the implementation of web services."],
    ["what is json", "JSON (JavaScript Object Notation) is a lightweight data interchange format that is easy for humans to read and write and easy for machines to parse and generate."],
    ["what is xml", "XML (Extensible Markup Language) is a markup language that defines rules for encoding documents in a format that is both human-readable and machine-readable."],
    ["what is a database", "A database is an organized collection of structured information or data, typically stored electronically in a computer system."],
    ["what is a query", "A query is a request for data or information from a database, usually written in SQL or another database query language."],
    ["what is an index", "An index is a database structure used to speed up the retrieval of rows from a table, similar to an index in a book."],
    ["what is a view", "A view is a virtual table in a database that presents data from one or more tables, often used to simplify complex queries."],
    ["what is normalization", "Normalization is the process of organizing data in a database to reduce redundancy and improve data integrity."],
    ["what is denormalization", "Denormalization is the process of intentionally introducing redundancy into a database to improve query performance."],
    ["what is a primary key", "A primary key is a unique identifier for a record in a database table, ensuring that each record is distinct."],
    ["what is a foreign key", "A foreign key is a field in one table that uniquely identifies a row of another table, used to establish relationships between the tables."],
    ["what is a transaction", "A transaction is a unit of work in a database management system that ensures consistency, isolation, and durability of the data."],
    ["what is acid", "ACID stands for Atomicity, Consistency, Isolation, and Durability – the properties that guarantee database transactions are processed reliably."],
    ["what is a subquery", "A subquery is a query nested inside another query, used to retrieve data that will be used by the outer query."],
    ["what is a join", "A join is an SQL operation used to combine data from two or more tables based on a related column between them."],
    ["what is an outer join", "An outer join is an SQL operation that returns all rows from one table and the matching rows from the other table, filling in nulls for non-matching rows."],
    ["what is an inner join", "An inner join is an SQL operation that returns only the rows that have matching values in both tables."],
    ["what is an oauth", "OAuth (Open Authorization) is an open standard for access delegation, allowing third-party applications to access user data without exposing passwords."],
    ["what is encryption", "Encryption is the process of converting data into a code to prevent unauthorized access, ensuring the confidentiality of the data."],
    ["what is decryption", "Decryption is the process of converting encrypted data back into its original form, allowing it to be read and understood."],
    ["what is a digital signature", "A digital signature is a cryptographic mechanism used to validate the authenticity and integrity of digital messages or documents."],
    ["what is public key cryptography", "Public key cryptography is a cryptographic system that uses two keys – a public key and a private key – to encrypt and decrypt data."],
    ["what is a certificate authority", "A Certificate Authority (CA) is an entity that issues digital certificates, which are used to verify the authenticity of public keys."],
    ["what is a key pair", "A key pair consists of a public key and a private key, used in public key cryptography to encrypt and decrypt data."],
    ["what is blockchain mining", "Blockchain mining is the process of validating transactions and adding them to a blockchain, usually through solving complex mathematical problems."],
    ["what is a consensus algorithm", "A consensus algorithm is a mechanism used in distributed systems, like blockchain, to ensure that all participants agree on the state of the system."],
    ["what is proof of work", "Proof of work is a consensus algorithm in which participants must solve complex mathematical puzzles to validate transactions and add them to the blockchain."],
    ["what is proof of stake", "Proof of stake is a consensus algorithm where participants validate transactions and create new blocks based on the number of coins they hold."],
    ["what is staking", "Staking is the process of locking up cryptocurrency to support the operations of a blockchain network, typically in proof of stake systems."],
    ["what is a blockchain fork", "A blockchain fork occurs when there is a divergence in the blockchain's protocol, resulting in two separate chains."],
    ["what is a tokenomics", "Tokenomics refers to the study and design of the economic system behind a cryptocurrency or token, including its supply, distribution, and incentives."],
    ["what is a decentralized finance", "Decentralized finance (DeFi) is a movement that uses blockchain technology to recreate traditional financial systems, like lending and borrowing, without intermediaries."],
    ["what is a liquidity pool", "A liquidity pool is a collection of funds locked in a smart contract that provides liquidity for decentralized exchanges or other DeFi platforms."],
    ["what is yield farming", "Yield farming is the practice of earning rewards by providing liquidity to DeFi protocols in the form of cryptocurrencies."],
    ["what is a governance token", "A governance token is a type of cryptocurrency that gives holders voting rights to influence decisions within a decentralized platform or network."],
    ["what is an nft", "An NFT (Non-Fungible Token) is a type of digital asset that represents ownership or proof of authenticity of a unique item or piece of content, usually based on blockchain technology."],
    ["what is a smart contract audit", "A smart contract audit is a review process that analyzes the code of a smart contract to identify vulnerabilities and ensure its security and correctness."],
    ["what is decentralized autonomous organization", "A Decentralized Autonomous Organization (DAO) is an organization that is governed by smart contracts and its community, without centralized control."],
    ["what is web3", "Web3 refers to the third era of the internet, characterized by decentralized, blockchain-based applications and services."],
    ["what is a metaverse", "The metaverse is a collective virtual shared space, created by the convergence of virtually enhanced physical reality and persistent digital environments."],
    ["what is augmented reality", "Augmented reality (AR) is a technology that overlays digital information, such as images or sounds, onto the real world."],
    ["what is virtual reality", "Virtual reality (VR) is an immersive technology that creates a simulated environment, allowing users to interact with it through special devices like headsets."],
    ["what is artificial intelligence ethics", "AI ethics refers to the study of moral issues and guidelines related to the development and application of AI systems, ensuring they align with human values."],
    ["what is privacy policy", "A privacy policy is a legal document that outlines how a company collects, stores, and uses personal data from its users."],
    ["what is GDPR", "The General Data Protection Regulation (GDPR) is a set of data protection and privacy laws in the European Union that govern how personal data is processed and protected."],
    ["what is data protection", "Data protection is the practice of safeguarding personal data from unauthorized access, use, or disclosure to ensure privacy and security."],
    ["what is a vpn", "A VPN (Virtual Private Network) is a service that encrypts your internet connection, protecting your online privacy and security by masking your IP address."],
    ["what is cloud computing", "Cloud computing is the delivery of computing services over the internet, allowing users to access data and applications remotely without needing local infrastructure."],
    ["what is a data center", "A data center is a physical facility used to store and manage large amounts of data, typically containing servers, storage devices, and networking equipment." ],
    ["what is machine learning", "Machine learning is a branch of artificial intelligence where systems can learn and improve from experience without being explicitly programmed."],
    ["what is supervised learning", "Supervised learning is a type of machine learning where the model is trained on labeled data to predict outcomes for new data."],
    ["what is unsupervised learning", "Unsupervised learning is a type of machine learning where the model is trained on unlabeled data to find patterns or groupings."],
    ["what is reinforcement learning", "Reinforcement learning is a type of machine learning where an agent learns by interacting with its environment and receiving rewards or penalties."],
    ["what is neural network", "A neural network is a set of algorithms designed to recognize patterns, inspired by the way the human brain operates."],
    ["what is deep learning", "Deep learning is a subset of machine learning that uses neural networks with many layers to analyze large datasets."],
    ["what is natural language processing", "Natural Language Processing (NLP) is a field of AI that focuses on enabling machines to understand, interpret, and respond to human language."],
    ["what is computer vision", "Computer vision is a field of AI that enables machines to interpret and make decisions based on visual data like images and videos."],
    ["what is a chatbot", "A chatbot is a software application designed to simulate human conversation through text or voice interactions."],
    ["what is sentiment analysis", "Sentiment analysis is the process of using AI to determine the emotional tone behind a piece of text, often used in customer feedback or social media analysis."],
    ["what is feature extraction", "Feature extraction is the process of reducing the dimensionality of data while preserving its most important characteristics for analysis."],
    ["what is overfitting", "Overfitting occurs when a machine learning model performs well on training data but fails to generalize to new, unseen data."],
    ["what is underfitting", "Underfitting occurs when a machine learning model is too simple to capture the underlying patterns in the data."],
    ["what is a confusion matrix", "A confusion matrix is a table used to evaluate the performance of a classification model by comparing predicted and actual labels."],
    ["what is precision in ml", "Precision is the ratio of correctly predicted positive observations to the total predicted positives in a classification model."],
    ["what is recall in ml", "Recall is the ratio of correctly predicted positive observations to all actual positives in a classification model."],
    ["what is f1 score", "The F1 score is the harmonic mean of precision and recall, used to evaluate the accuracy of a classification model."],
    ["what is gradient descent", "Gradient descent is an optimization algorithm used to minimize a function by iteratively moving towards the steepest descent direction."],
    ["what is a cost function", "A cost function measures the difference between predicted values and actual values in a machine learning model."],
    ["what is a loss function", "A loss function is a mathematical function that quantifies the error between predicted and actual outputs in machine learning."],
    ["what is an epoch in ml", "An epoch refers to one complete pass through the entire training dataset during the training of a machine learning model."],
    ["what is a batch size", "Batch size is the number of training examples processed together before updating the model weights in machine learning."],
    ["what is backpropagation", "Backpropagation is an algorithm used to train neural networks by propagating errors backward and updating weights."],
    ["what is a learning rate", "Learning rate is a hyperparameter that determines the step size at each iteration while optimizing a model's weights."],
    ["what is k-means clustering", "K-means clustering is an unsupervised learning algorithm used to group data into clusters based on similarity."],
    ["what is decision tree", "A decision tree is a flowchart-like structure used for classification and regression, where decisions are made at each node."],
    ["what is random forest", "Random forest is an ensemble learning method that uses multiple decision trees to improve accuracy and prevent overfitting."],
    ["what is svm", "Support Vector Machine (SVM) is a supervised learning algorithm used for classification and regression by finding the best hyperplane."],
    ["what is k-nearest neighbors", "K-Nearest Neighbors (KNN) is a simple algorithm that classifies data based on the majority class of its nearest neighbors."],
    ["what is data preprocessing", "Data preprocessing involves preparing raw data for analysis by cleaning, transforming, and organizing it into a usable format."],
    ["what is one-hot encoding", "One-hot encoding is a technique used to convert categorical data into binary vectors for machine learning models."],
    ["what is dimensionality reduction", "Dimensionality reduction is the process of reducing the number of features in a dataset while preserving its most important information."],
    ["what is principal component analysis", "Principal Component Analysis (PCA) is a technique used for dimensionality reduction by transforming data into a set of orthogonal components."],
    ["what is t-SNE", "t-SNE (t-Distributed Stochastic Neighbor Embedding) is a technique for visualizing high-dimensional data in two or three dimensions."],
    ["what is bagging in ml", "Bagging, or Bootstrap Aggregating, is an ensemble method that combines predictions from multiple models to improve performance and reduce variance."],
    ["what is boosting in ml", "Boosting is an ensemble method that combines weak learners sequentially to create a strong model by focusing on errors made by previous learners."],
    ["what is ada boost", "AdaBoost (Adaptive Boosting) is a boosting technique that adjusts the weights of weak learners to improve their accuracy on misclassified data."],
    ["what is gradient boosting", "Gradient Boosting is an ensemble method that builds models sequentially, minimizing errors using gradient descent."],
    ["what is xgboost", "XGBoost (Extreme Gradient Boosting) is a powerful, efficient implementation of gradient boosting for supervised learning tasks."],
    ["what is bag of words", "Bag of Words (BoW) is a text representation method that counts word occurrences without considering word order or context."],
    ["what is word embedding", "Word embedding is a technique that represents words as dense vectors in a continuous vector space, capturing semantic meaning."],
    ["what is word2vec", "Word2Vec is a neural network-based model used to create word embeddings by analyzing word contexts in a corpus."],
    ["what is glove", "GloVe (Global Vectors for Word Representation) is a word embedding technique that captures word meanings by analyzing word co-occurrence statistics."],
    ["what is rnn", "RNN (Recurrent Neural Network) is a type of neural network designed for sequential data, like time series or text."],
    ["what is lstm", "LSTM (Long Short-Term Memory) is a type of RNN designed to overcome the vanishing gradient problem, making it effective for long sequences."],
    ["what is gru", "GRU (Gated Recurrent Unit) is a simplified version of LSTM, designed for sequential data processing with fewer parameters."],
    ["what is bert", "BERT (Bidirectional Encoder Representations from Transformers) is a transformer-based model for natural language understanding tasks."],
    ["what is gpt", "GPT (Generative Pre-trained Transformer) is a transformer-based model designed for generating human-like text and language understanding."],
    ["what is transfer learning", "Transfer learning is a technique where a pre-trained model is fine-tuned on a new, related task to improve performance."],
    ["what is an autoencoder", "An autoencoder is a neural network used for unsupervised learning by encoding data into a compressed representation and reconstructing it."],
    ["what is a gan", "GAN (Generative Adversarial Network) is a type of neural network where two models, a generator and a discriminator, compete to create realistic data samples."],
    ["what is the internet", "The Internet is a global network of interconnected computers and servers that communicate using standardized protocols."],
    ["what is an IP address", "An IP address is a unique numerical label assigned to a device on a network, allowing it to communicate over the Internet."],
    ["what is the difference between http and https", "HTTP is unsecured, while HTTPS is a secure version of HTTP, using encryption to protect data."],
    ["what is a browser", "A browser is software that allows you to access and interact with websites on the internet, such as Chrome or Firefox."],
    ["what is an operating system", "An operating system is software that manages computer hardware and software, enabling other programs to run."],
    ["what is linux", "Linux is an open-source operating system widely used for servers, development, and personal computing."],
    ["what is virtual reality", "Virtual Reality (VR) is a simulated experience that can replicate the real world or create entirely new environments."],
    ["what is augmented reality", "Augmented Reality (AR) enhances the real world by overlaying digital objects or information onto the physical environment."],
    ["what is blockchain", "Blockchain is a decentralized ledger technology used for securely recording transactions across multiple computers."],
    ["what is bitcoin", "Bitcoin is a digital currency that operates on blockchain technology, allowing for decentralized and secure transactions."],
    ["what is an NFT", "NFT (Non-Fungible Token) is a digital asset that represents ownership of unique items like art, music, or videos on a blockchain."],
    ["what is a smart contract", "A smart contract is a self-executing program on a blockchain that enforces terms and agreements automatically."],
    ["what is cloud storage", "Cloud storage is a service that allows you to store and access data on remote servers hosted on the internet."],
    ["what is a VPN", "A VPN (Virtual Private Network) secures your internet connection by encrypting data and masking your IP address."],
    ["what is cybersecurity", "Cybersecurity involves protecting computer systems and networks from unauthorized access or attacks."],
    ["how do airplanes fly", "Airplanes fly using the principles of lift, thrust, and aerodynamics to counteract gravity and drag."],
    ["how do satellites work", "Satellites orbit Earth and communicate with ground stations to perform tasks like GPS, communication, and imaging."],
    ["why is the sky blue", "The sky appears blue because air molecules scatter blue light from the Sun more than other colors."],
    ["why do we dream", "Dreaming is a natural part of the sleep cycle, thought to help process emotions, memories, and problem-solving."],
    ["what is the speed of light", "The speed of light is approximately 299,792 kilometers per second (or about 186,282 miles per second)."],
    ["what is gravity", "Gravity is the force that attracts two objects with mass towards each other, keeping us grounded on Earth."],
    ["what is evolution", "Evolution is the process by which species of organisms change over time through natural selection and adaptation."],
    ["what is DNA", "DNA (Deoxyribonucleic Acid) is a molecule that carries the genetic instructions used in the growth and functioning of living organisms."],
    ["what is the human brain", "The human brain is a complex organ that controls thought, memory, emotion, touch, motor skills, and other functions."],
    ["what is artificial intelligence", "Artificial Intelligence (AI) is the simulation of human intelligence in machines that can perform tasks requiring cognition."],
    ["what is a meme", "A meme is a cultural idea or trend, often humorous, spread through social media in the form of images, videos, or text."],
    ["what is the meaning of life", "The meaning of life varies from person to person, often revolving around purpose, happiness, and relationships."],
    ["what is love", "Love is a deep emotion of affection, care, and connection towards someone or something."],
    ["what is happiness", "Happiness is a state of well-being and contentment, often influenced by life satisfaction and positive emotions."],
    ["who is the richest person in the world", "This frequently changes, but it is usually someone like Elon Musk or Jeff Bezos."],
    ["what is the tallest mountain in the world", "Mount Everest is the tallest mountain in the world, standing at 8,848.86 meters (29,031.7 feet) above sea level."],
    ["what is the largest desert in the world", "The Antarctic Desert is the largest desert, followed by the Sahara Desert in terms of non-polar deserts."],
    ["what is the longest river in the world", "The Nile River is traditionally considered the longest, though some studies argue for the Amazon River."],
    ["what is the largest animal in the world", "The blue whale is the largest animal, growing up to 100 feet long and weighing over 200 tons."],
    ["what is the fastest animal on land", "The cheetah is the fastest land animal, capable of speeds up to 60-70 mph (97-113 km/h)."],
    ["what is the oldest language in the world", "Tamil is often considered one of the oldest languages still spoken today."],
    ["what is the most spoken language in the world", "English and Mandarin Chinese are among the most spoken languages worldwide."],
    ["what is the largest country in the world", "Russia is the largest country in the world by area."],
    ["what is the smallest country in the world", "Vatican City is the smallest country in the world by both area and population."],
    ["what is the coldest place on earth", "Antarctica is the coldest place on Earth, with temperatures dropping below -89°C (-128°F)."],
    ["what is the hottest place on earth", "Death Valley in California, USA, holds the record for the hottest temperature ever recorded."],
    ["what is space", "Space is the vast, seemingly infinite expanse beyond Earth's atmosphere."],
    ["how does a rocket work", "Rockets work by expelling exhaust gases at high speed, creating thrust according to Newton's third law of motion."],
    ["what is time travel", "Time travel refers to the concept of moving between different points in time, commonly seen in science fiction."],
    ["what is teleportation", "Teleportation is the hypothetical transfer of matter or energy from one point to another without traversing the physical space between them."],
    ["what is quantum physics", "Quantum physics studies the behavior of particles at the atomic and subatomic levels."],
    ["what is a black hole", "A black hole is a region in space with a gravitational pull so strong that nothing, not even light, can escape it."],
    ["what is the universe", "The universe encompasses all of space, time, matter, and energy, including galaxies, stars, and planets."],
    ["what is the Milky Way", "The Milky Way is the galaxy that contains our solar system, appearing as a band of light in the night sky."],
    ["what is the Big Bang", "The Big Bang is the leading theory explaining the origin of the universe, occurring around 13.8 billion years ago."],
    ["what is an asteroid", "An asteroid is a small rocky body orbiting the Sun, mostly found in the asteroid belt between Mars and Jupiter."],
    ["what is a comet", "A comet is an icy body that releases gas or dust, forming a tail when it approaches the Sun."],
    ["what is a supernova", "A supernova is the explosion of a star, resulting in a bright and powerful burst of energy."],
    ["what is a galaxy", "A galaxy is a massive system of stars, planets, gas, and dust bound together by gravity."],
    ["what is a planet", "A planet is a celestial body orbiting a star, massive enough to be rounded by its own gravity."],
    ["what is Earth", "Earth is the third planet from the Sun, the only known planet to support life, and home to diverse ecosystems."],
    ["what is the most popular food in the world", "Pizza is often considered one of the most popular foods globally."],
    ["what is the rarest color in nature", "Blue is considered one of the rarest colors in nature."],
    ["what is the tallest tree in the world", "The tallest tree is a coast redwood named Hyperion, standing at 379.7 feet (115.7 meters)."],
    ["what is the fastest bird in the world", "The peregrine falcon is the fastest bird, capable of reaching speeds over 240 mph in a dive."],
    ["what is the smallest bird in the world", "The bee hummingbird is the smallest bird, measuring about 2 inches in length."],
    ["what is the most expensive spice in the world", "Saffron is the most expensive spice, costing up to $5,000 per kilogram."],
    ["what is the hardest natural substance", "Diamond is the hardest natural substance on Earth."],
    ["what is the heaviest animal in the world", "The blue whale is the heaviest, weighing over 200 tons."],
    ["what is the largest flower in the world", "The Rafflesia arnoldii produces the largest individual flower, measuring up to 3 feet in diameter."],
    ["what is the longest word in the English language", "The longest word is pneumonoultramicroscopicsilicovolcanoconiosis, a type of lung disease."],
    ["what is the most common phobia", "Arachnophobia, the fear of spiders, is one of the most common phobias."],
    ["what is the most used letter in English", "The letter 'E' is the most commonly used letter in English."],
    ["what is the most spoken word in the world", "'OK' is considered the most spoken word globally."],
    ["what is the oldest book in the world", "The 'Epic of Gilgamesh' is one of the oldest known literary works."],
    ["what is the hottest pepper in the world", "The Carolina Reaper is considered the hottest chili pepper."],
    ["what is the largest ocean in the world", "The Pacific Ocean is the largest ocean, covering more than 63 million square miles."],
    ["what is the smallest mammal in the world", "The bumblebee bat, also called Kitti's hog-nosed bat, is the smallest mammal."],
    ["what is the largest mammal in the world", "The blue whale holds the title as the largest mammal."],
    ["what is the oldest tree in the world", "Methuselah, a bristlecone pine in California, is one of the oldest known trees, over 4,800 years old."],
    ["what is the deepest point in the ocean", "The Mariana Trench's Challenger Deep is the deepest point, at about 36,000 feet."],
    ["what is the most visited city in the world", "Bangkok, Thailand, is often cited as one of the most visited cities."],
    ["what is the longest movie ever made", "The movie 'Logistics' is the longest, running for 857 hours (35 days and 17 hours)."],
    ["what is the most popular video game", "Minecraft is one of the most popular video games ever, with over 200 million copies sold."],
    ["what is the oldest sport", "Wrestling is considered one of the oldest sports, dating back to ancient civilizations."],
    ["what is the most popular sport in the world", "Soccer (football) is the most popular sport worldwide."],
    ["what is the most expensive painting in the world", "'Salvator Mundi' by Leonardo da Vinci is one of the most expensive paintings ever sold."],
    ["what is the brightest star in the night sky", "Sirius, also known as the Dog Star, is the brightest star visible from Earth."],
    ["what is the most popular movie of all time", "This depends on criteria, but 'Avatar' is the highest-grossing movie."],
    ["what is the most downloaded app", "TikTok is one of the most downloaded apps globally."],
    ["what is the longest river in Africa", "The Nile River is the longest river in Africa."],
    ["what is the most popular holiday in the world", "Christmas is widely celebrated as one of the most popular holidays globally."],
    ["what is the largest island in the world", "Greenland is the largest island in the world."],
    ["what is the most dangerous animal in the world", "The mosquito, due to its role in spreading diseases, is considered the most dangerous."],
    ["what is the most venomous snake", "The inland taipan, also known as the 'fierce snake,' is the most venomous."],
    ["what is the oldest university in the world", "The University of Al-Qarawiyyin in Morocco, established in 859 AD, is the oldest."],
    ["what is the most common element in the universe", "Hydrogen is the most common element in the universe."],
    ["what is the hardest language to learn", "Mandarin Chinese is often cited as one of the hardest languages to learn."],
    ["what is the most widely eaten food in the world", "Rice is one of the most widely consumed staple foods."],
    ["what is the oldest musical instrument", "The flute is one of the oldest known musical instruments."],
    ["what is the largest coral reef in the world", "The Great Barrier Reef in Australia is the largest coral reef."],
    ["what is the smallest fish in the world", "The Paedocypris, a type of carp, is the smallest fish, measuring just 7.9 millimeters."],
    ["what is the fastest-growing plant", "Bamboo is the fastest-growing plant, capable of growing up to 35 inches per day."],
    ["what is the oldest living animal", "The Greenland shark is one of the oldest known animals, living over 400 years."],
    ["what is the most intelligent animal after humans", "Dolphins are considered highly intelligent and second only to humans in cognitive abilities."],
    ["what is the rarest gemstone", "Painite is one of the rarest gemstones in the world."],
    ["what is the longest word in the dictionary", "The longest word is 'pneumonoultramicroscopicsilicovolcanoconiosis.'"],
    ["what is the world's most popular drink", "Water is the most consumed drink, but tea is the most popular prepared beverage."],
    ["what is the lightest element", "Hydrogen is the lightest and most abundant element in the universe."],
    ["what is the largest bird in the world", "The ostrich is the largest bird, standing up to 9 feet tall."],
    ["what is the oldest coin in the world", "The Lydian Lion, minted around 600 BC, is the world's oldest known coin."],
    ["what is the most expensive car in the world", "The Bugatti La Voiture Noire is one of the most expensive cars, priced at over $18 million."],
    ["what is the largest cave in the world", "The Sơn Đoòng cave in Vietnam is the largest cave by volume."],
    ["what is the hottest planet in the solar system", "Venus is the hottest planet, with surface temperatures over 450°C (840°F)."],
    # General Knowledge
    ["what is the capital of france", "The capital of France is Paris."],
    ["who is known as the father of computers", "Charles Babbage is known as the father of computers."],
    ["what is the largest country in the world", "Russia is the largest country in the world by area."],
    ["what is the smallest country in the world", "Vatican City is the smallest country in the world."],
    ["how many continents are there in the world", "There are 7 continents in the world."],
    
    # Science
    ["what planet is known as the red planet", "Mars is known as the Red Planet."],
    ["what is the chemical symbol for water", "The chemical symbol for water is H2O."],
    ["what is the speed of light", "The speed of light is approximately 299,792 kilometers per second."],
    ["what is the largest organ in the human body", "The skin is the largest organ in the human body."],
    ["what gas do plants absorb from the atmosphere", "Plants absorb carbon dioxide from the atmosphere."],
    
    # History
    ["who was the first president of the united states", "George Washington was the first President of the United States."],
    ["when was the declaration of independence signed", "The Declaration of Independence was signed on July 4, 1776."],
    ["who discovered america", "Christopher Columbus is credited with discovering America in 1492."],
    ["what year did world war ii end", "World War II ended in 1945."],
    ["who built the taj mahal", "The Taj Mahal was built by Mughal Emperor Shah Jahan."],
    
    # Entertainment
    ["what is the highest-grossing movie of all time", "'Avatar' is the highest-grossing movie of all time."],
    ["who is the author of harry potter", "J.K. Rowling is the author of the Harry Potter series."],
    ["what is the longest-running tv show", "'The Simpsons' is the longest-running TV show."],
    ["what is the most popular video streaming platform", "YouTube is the most popular video streaming platform."],
    ["what is the most popular genre of music", "Pop is one of the most popular genres of music."],
    
    # Fun Trivia
    ["what is the tallest mountain in the world", "Mount Everest is the tallest mountain in the world."],
    ["what is the smallest bone in the human body", "The stapes bone in the middle ear is the smallest bone in the human body."],
    ["what animal is known as the king of the jungle", "The lion is known as the king of the jungle."],
    ["what is the largest desert in the world", "The Sahara Desert is the largest hot desert in the world."],
    ["what is the coldest place on earth", "Antarctica is the coldest place on Earth."],
    
    # Technology
    ["who founded microsoft", "Microsoft was founded by Bill Gates and Paul Allen."],
    ["what does cpu stand for", "CPU stands for Central Processing Unit."],
    ["what year was the first iphone released", "The first iPhone was released in 2007."],
    ["what is the most used programming language", "Python is one of the most widely used programming languages."],
    ["what is the full form of www", "WWW stands for World Wide Web."],
    
    # Geography
    ["what is the longest river in the world", "The Nile River is considered the longest river in the world."],
    ["what country has the most population", "China has the largest population in the world."],
    ["what is the capital of japan", "The capital of Japan is Tokyo."],
    ["which ocean is the largest", "The Pacific Ocean is the largest ocean in the world."],
    ["what is the hottest desert in the world", "The Lut Desert in Iran is the hottest desert in the world."],
    
    # Sports
    ["who has won the most olympic medals", "Michael Phelps has won the most Olympic medals."],
    ["what sport is known as the king of sports", "Soccer (football) is known as the King of Sports."],
    ["what is the national sport of india", "Hockey is considered the national sport of India."],
    ["who is the fastest man in the world", "Usain Bolt is considered the fastest man in the world."],
    ["what is the size of a basketball hoop", "A basketball hoop has a diameter of 18 inches."],
    
    # Literature
    ["who wrote romeo and juliet", "William Shakespeare wrote 'Romeo and Juliet.'"],
    ["what is the first book of the bible", "Genesis is the first book of the Bible."],
    ["who wrote pride and prejudice", "Jane Austen wrote 'Pride and Prejudice.'"],
    ["what is the longest novel ever written", "'In Search of Lost Time' by Marcel Proust is considered the longest novel."],
    ["who wrote the great gatsby", "F. Scott Fitzgerald wrote 'The Great Gatsby.'"],
    
    # Mythology
    ["who is the king of the greek gods", "Zeus is the king of the Greek gods."],
    ["what is thor the god of", "Thor is the Norse god of thunder."],
    ["who was the egyptian god of the underworld", "Osiris was the Egyptian god of the underworld."],
    ["what is the roman name for hera", "The Roman name for Hera is Juno."],
    ["what is the name of the greek god of the sea", "Poseidon is the Greek god of the sea."],
    
    # Health and Fitness
    ["how many calories are in a pound of fat", "There are approximately 3,500 calories in a pound of fat."],
    ["what is the normal body temperature", "The normal body temperature is around 98.6°F (37°C)."],
    ["how many bones are in the human body", "An adult human body has 206 bones."],
    ["what is the best way to stay hydrated", "Drinking water is the best way to stay hydrated."],
    ["what vitamin is produced by the body when exposed to sunlight", "Vitamin D is produced when the body is exposed to sunlight."],
    
    # Space
    ["what is the smallest planet in the solar system", "Mercury is the smallest planet in the solar system."],
    ["what is the largest planet in the solar system", "Jupiter is the largest planet in the solar system."],
    ["how many moons does mars have", "Mars has two moons, Phobos and Deimos."],
    ["what is the closest star to earth", "The Sun is the closest star to Earth."],
    ["what galaxy is earth located in", "Earth is located in the Milky Way galaxy."],
    
    # Animals
    ["what is the fastest land animal", "The cheetah is the fastest land animal."],
    ["what is the largest land animal", "The African elephant is the largest land animal."],
    ["what is the lifespan of a giant tortoise", "A giant tortoise can live over 100 years."],
    ["what bird can fly backward", "The hummingbird is the only bird that can fly backward."],
    ["what is the largest fish in the ocean", "The whale shark is the largest fish in the ocean."],
    
    # Fun Facts
    ["what is the only fruit with seeds on the outside", "The strawberry is the only fruit with seeds on the outside."],
    ["how many hearts does an octopus have", "An octopus has three hearts."],
    ["what is the most consumed drink in the world after water", "Tea is the most consumed drink after water."],
    ["what is the only mammal that can fly", "The bat is the only mammal capable of true flight."],
    ["how many taste buds does the average human tongue have", "The average human tongue has about 10,000 taste buds."],
    
    # Riddles
    ["what has to be broken before you can use it", "An egg!"],
    ["what has keys but can’t open locks", "A piano."],
    ["what comes once in a minute, twice in a moment, but never in a thousand years", "The letter 'M'."],
    ["what has a face and two hands but no arms or legs", "A clock."],
    ["what can travel around the world while staying in the same spot", "A stamp."]

]

#imports
from speech import say
def open_response(query):
        for q in responses:
            try:
                if f"{q[0]}".lower() in query.lower():
                    ans = (f"{q[1]} .")
                    print(f"User: {query}\n Bharat A.I: {ans}\n")
                    say(ans)
                    
            except Exception as e:
                print("Error : ",e)
                say("An error oucurred. unable to understand question  sir...")
         